### ISSUE TITLE
is there love.graphics.translate or analog

### ISSUE THREAD

**Issue by boris-741** [apicici/cimgui-love#16]
is there an analogue of love.graphics.translate for imgi? I wanted to move the global coordinates of all windows at the same time without changing the position of each individually

----------------------------

i want to create similar functionality on https://github.com/thedmd/imgui-node-editor

**Comment by apicici** [comment]
I don't think there's a completely straightforward way of doing that, but if you are trying to recreate the canvas functionality from the node editor you can try to reimplement [this](https://github.com/thedmd/imgui-node-editor/blob/master/imgui_canvas.cpp) directly in Lua using the appropriate cimgui functions. This requires enough familiarity with C++ to understand that code, though.

You could also ask directly on the Dear ImGui  repository.

**Comment by boris-741** [comment]
thanks i'll take a look
