### ISSUE TITLE
Rounding property in styles does not affect windows

### ISSUE THREAD

**Issue by Yeahyay** [apicici/cimgui-love#19]
When setting the `FrameRounding` and `GrabRounding`  style properties, only the docking icons that pop up seem to be affected.

```lua
local ImGui = require("lib.cimgui")
local style = ImGui.GetStyle();
style.FrameRounding = 20;
style.GrabRounding = 2;
```
![image](https://github.com/apicici/cimgui-love/assets/34212037/167013de-21c7-4904-9107-5da14ba94e58)

**Comment by apicici** [comment]
Is the problem that you are also expecting the windows to be rounded?

**Comment by apicici** [comment]
The window rounding is controlled through a different property (`WindowRounding`). I would recommend activating the style editor (through `ShowStyleEditor`) for playing around with this kind of things.
