### ISSUE TITLE
Error on module import when window is not yet initialized

### ISSUE THREAD

**Issue by majorcob** [apicici/cimgui-love#8]
The `Alpha8_shader` initialization in love.lua calls `love.graphics.newShader`, which raises an error when the module is imported if the window is not yet initialized (for example, when https://love2d.org/wiki/Config_Files#window is set to `nil`).

```
Error: lib/cimgui/love.lua:181: love.graphics cannot function without a window!
```

Could this be instead set up during `Init()`, or some other time where we can assume that the window has been created?

**Comment by apicici** [comment]
Thanks for pointing this out, I will change it so that the shader is created by the `Init` function.
