### ISSUE TITLE
UI is broken under highdpi mode 

### ISSUE THREAD

**Issue by zhengying** [apicici/cimgui-love#9]
on macOS,  when t.window.highdpi = true
UI is broken.
<img width="626" alt="Screen Shot 2022-07-28 at 8 39 44 PM" src="https://user-images.githubusercontent.com/1042545/181507371-c46f5e8a-f69c-48ea-8b1c-4fe1787d59f7.png">

**Comment by apicici** [comment]
I have tested highdpi mode on Linux without problems. Does this happen if you run the test file (the Lua code in the README)? If not, could you send me the code you are using in your test so I can try it?

**Comment by zhengying** [comment]
Sorry! I downloaded the old example on the love2d forum, I just tried the new release library, and It's working well.
cimage-love is an excellent library, thanks for your hard work!

**Comment by apicici** [comment]
Great! I have changed a lot of stuff since that first release, including highdpi related things. I'm glad you like the library!
